<?
require($_SERVER["DOCUMENT_ROOT"]."/bitrix/header.php");
$APPLICATION->SetTitle("Каталог");
?><?$APPLICATION->IncludeComponent(
	"alexkova.emarket:catalog", 
	".default", 
	array(
		"IBLOCK_TYPE" => "catalog",
		"IBLOCK_ID" => "#PRODUCT_IBLOCK_ID#",
		"HIDE_NOT_AVAILABLE" => "Y",
		"TEMPLATE_THEME" => "",
		"SHOW_DISCOUNT_PERCENT" => "Y",
		"SHOW_OLD_PRICE" => "Y",
		"DETAIL_SHOW_MAX_QUANTITY" => "Y",
		"MESS_BTN_BUY" => "Купить",
		"MESS_BTN_ADD_TO_BASKET" => "В корзину",
		"MESS_BTN_COMPARE" => "Сравнение",
		"MESS_BTN_DETAIL" => "Подробнее",
		"MESS_NOT_AVAILABLE" => "Нет в наличии",
		"DETAIL_USE_VOTE_RATING" => "Y",
		"DETAIL_USE_COMMENTS" => "Y",
		"DETAIL_BRAND_USE" => "Y",
		"SECTION_ID_VARIABLE" => "SECTION_CODE",
		"SEF_MODE" => "Y",
		"AJAX_MODE" => "N",
		"AJAX_OPTION_JUMP" => "N",
		"AJAX_OPTION_STYLE" => "Y",
		"AJAX_OPTION_HISTORY" => "N",
		"CACHE_TYPE" => "A",
		"CACHE_TIME" => "3600",
		"CACHE_FILTER" => "N",
		"CACHE_GROUPS" => "Y",
		"SET_STATUS_404" => "N",
		"SET_TITLE" => "Y",
		"ADD_SECTIONS_CHAIN" => "Y",
		"ADD_ELEMENT_CHAIN" => "N",
		"USE_ELEMENT_COUNTER" => "Y",
		"USE_FILTER" => "Y",
		"FILTER_VIEW_MODE" => "VERTICAL",
		"USE_REVIEW" => "Y",
		"USE_COMPARE" => "Y",
		"PRICE_CODE" => array(
			0 => "BASE",
		),
		"USE_PRICE_COUNT" => "N",
		"SHOW_PRICE_COUNT" => "0",
		"PRICE_VAT_INCLUDE" => "Y",
		"PRICE_VAT_SHOW_VALUE" => "N",
		"CONVERT_CURRENCY" => "N",
		"BASKET_URL" => "#SITE_DIR#personal/basket.php",
		"ACTION_VARIABLE" => "action",
		"PRODUCT_ID_VARIABLE" => "id",
		"USE_PRODUCT_QUANTITY" => "Y",
		"ADD_PROPERTIES_TO_BASKET" => "Y",
		"PRODUCT_PROPS_VARIABLE" => "prop",
		"PARTIAL_PRODUCT_PROPERTIES" => "N",
		"PRODUCT_PROPERTIES" => array(
		),
		"SHOW_TOP_ELEMENTS" => "Y",
		"TOP_ELEMENT_COUNT" => "9",
		"TOP_LINE_ELEMENT_COUNT" => "3",
		"TOP_ELEMENT_SORT_FIELD" => "PROPERTY_NEW",
		"TOP_ELEMENT_SORT_ORDER" => "desc",
		"TOP_ELEMENT_SORT_FIELD2" => "",
		"TOP_ELEMENT_SORT_ORDER2" => "",
		"TOP_PROPERTY_CODE" => array(
			0 => "",
			1 => "",
		),
		"SECTION_COUNT_ELEMENTS" => "Y",
		"SECTION_TOP_DEPTH" => "2",
		"SECTIONS_VIEW_MODE" => "LIST",
		"SECTIONS_SHOW_PARENT_NAME" => "Y",
		"PAGE_ELEMENT_COUNT" => "12",
		"LINE_ELEMENT_COUNT" => "3",
		"ELEMENT_SORT_FIELD" => "",
		"ELEMENT_SORT_ORDER" => "",
		"ELEMENT_SORT_FIELD2" => "",
		"ELEMENT_SORT_ORDER2" => "",
		"LIST_PROPERTY_CODE" => array(
			0 => "MATERIAL",
			1 => "COLOR",
			2 => "SPECIALOFFER",
			3 => "NEWPRODUCT",
			4 => "SALELEADER",
			5 => "RECOMMENDED",
			6 => "MANUFACTURER",
			7 => "MINIMUM_PRICE",
			8 => "MAXIMUM_PRICE",
			9 => "CML2_BAR_CODE",
			10 => "CML2_ARTICLE",
			11 => "CML2_ATTRIBUTES",
			12 => "CML2_TRAITS",
			13 => "CML2_BASE_UNIT",
			14 => "CML2_TAXES",
			15 => "vote_count",
			16 => "vote_sum",
			17 => "rating",
			18 => "BLOG_POST_ID",
			19 => "BLOG_COMMENTS_CNT",
			20 => "WIDTH",
			21 => "LENGHT",
			22 => "SIZE",
			23 => "HEIGHT",
			24 => "RECOMMEND",
			25 => "",
		),
		"INCLUDE_SUBSECTIONS" => "Y",
		"LIST_META_KEYWORDS" => "-",
		"LIST_META_DESCRIPTION" => "-",
		"LIST_BROWSER_TITLE" => "-",
		"DETAIL_PROPERTY_CODE" => array(
			0 => "MATERIAL",
			1 => "COLOR",
			2 => "SPECIALOFFER",
			3 => "MECH_KOL",
			4 => "SUVENIR_NAZNACH",
			5 => "GLASS_OS",
			6 => "VELO_NAGRUZKA",
			7 => "PAL_TYPE",
			8 => "VELO_TYPE",
			9 => "PLATFORM",
			10 => "COMPLECT",
			11 => "ARB_TIME",
			12 => "CAMERA_TYPE",
			13 => "GLASS_TYPE",
			14 => "MANUFACTURER",
			15 => "DISPLAY_TYPE",
			16 => "ENERGY_TYPE",
			17 => "MATRIX_TYPE",
			18 => "CAMERA_POSITION",
			19 => "GLASS_CPU",
			20 => "DIAGONAL",
			21 => "ARB_CHANNEL",
			22 => "VOLUME",
			23 => "PX_SUMM",
			24 => "MATRIX",
			25 => "GLASS_ALL",
			26 => "OBJOM_VSTROENNOY_PAMYATI",
			27 => "SIZE_ACCUMUL",
			28 => "FORM_FACTOR",
			29 => "DYSPLAY_CAM",
			30 => "VIDEO_RESIZED",
			31 => "SUMM_SIM",
			32 => "CHASTOTA",
			33 => "PERSONAL_SIZE",
			34 => "FORMAT_SIM",
			35 => "IMPEDANS",
			36 => "WIDTH",
			37 => "LENGHT",
			38 => "SIZE",
			39 => "HEIGHT",
			40 => "RECOMMEND",
			41 => "",
		),
		"DETAIL_META_KEYWORDS" => "-",
		"DETAIL_META_DESCRIPTION" => "-",
		"DETAIL_BROWSER_TITLE" => "-",
		"DETAIL_DISPLAY_NAME" => "Y",
		"DETAIL_DETAIL_PICTURE_MODE" => "POPUP",
		"DETAIL_ADD_DETAIL_TO_SLIDER" => "Y",
		"DETAIL_DISPLAY_PREVIEW_TEXT_MODE" => "H",
		"LINK_IBLOCK_TYPE" => "",
		"LINK_IBLOCK_ID" => "",
		"LINK_PROPERTY_SID" => "",
		"LINK_ELEMENTS_URL" => "link.php?PARENT_ELEMENT_ID=#ELEMENT_ID#",
		"USE_ALSO_BUY" => "Y",
		"USE_STORE" => "N",
		"PAGER_TEMPLATE" => "",
		"DISPLAY_TOP_PAGER" => "N",
		"DISPLAY_BOTTOM_PAGER" => "Y",
		"PAGER_TITLE" => "Товары",
		"PAGER_SHOW_ALWAYS" => "N",
		"PAGER_DESC_NUMBERING" => "N",
		"PAGER_DESC_NUMBERING_CACHE_TIME" => "36000",
		"PAGER_SHOW_ALL" => "N",
		"TOP_VIEW_MODE" => "BANNER",
		"ADD_PICT_PROP" => "MORE_PHOTO",
		"LABEL_PROP" => "-",
		"TOP_ROTATE_TIMER" => "30",
		"SEF_FOLDER" => "#SITE_DIR#catalog/",
		"AJAX_OPTION_ADDITIONAL" => "",
		"PRODUCT_QUANTITY_VARIABLE" => "quantity",
		"DETAIL_VOTE_DISPLAY_AS_RATING" => "rating",
		"MESSAGES_PER_PAGE" => "10",
		"USE_CAPTCHA" => "Y",
		"REVIEW_AJAX_POST" => "N",
		"PATH_TO_SMILE" => "/bitrix/images/forum/smile/",
		"FORUM_ID" => "#EMARKET_FORUM_ID#",
		"URL_TEMPLATES_READ" => "",
		"SHOW_LINK_TO_FORUM" => "N",
		"DETAIL_BLOG_USE" => "Y",
		"DETAIL_VK_USE" => "N",
		"DETAIL_FB_USE" => "N",
		"DETAIL_BLOG_URL" => "catalog_comments",
		"DETAIL_VK_API_ID" => "API_ID",
		"USE_STORE_PHONE" => "Y",
		"USE_STORE_SCHEDULE" => "Y",
		"USE_MIN_AMOUNT" => "Y",
		"MIN_AMOUNT" => "10",
		"STORE_PATH" => "#SITE_DIR#company/#store_id#",
		"MAIN_TITLE" => "Наличие на складах",
		"OFFERS_CART_PROPERTIES" => array(
		),
		"TOP_OFFERS_FIELD_CODE" => array(
			0 => "NAME",
			1 => "",
		),
		"TOP_OFFERS_PROPERTY_CODE" => array(
			0 => "",
			1 => "",
		),
		"TOP_OFFERS_LIMIT" => "5",
		"LIST_OFFERS_FIELD_CODE" => array(
			0 => "NAME",
			1 => "",
		),
		"LIST_OFFERS_PROPERTY_CODE" => array(
			0 => "",
			1 => "",
		),
		"LIST_OFFERS_LIMIT" => "5",
		"DETAIL_OFFERS_FIELD_CODE" => array(
			0 => "NAME",
			1 => "",
		),
		"DETAIL_OFFERS_PROPERTY_CODE" => array(
			0 => "VOLUME",
			1 => "COLOR",
			2 => "",
		),
		"OFFERS_SORT_FIELD" => "sort",
		"OFFERS_SORT_ORDER" => "asc",
		"OFFERS_SORT_FIELD2" => "id",
		"OFFERS_SORT_ORDER2" => "desc",
		"PRODUCT_DISPLAY_MODE" => "N",
		"OFFER_ADD_PICT_PROP" => "-",
		"OFFER_TREE_PROPS" => array(
			0 => "-",
		),
		"FILTER_NAME" => "",
		"FILTER_FIELD_CODE" => array(
			0 => "",
			1 => "",
		),
		"FILTER_PROPERTY_CODE" => array(
			0 => "MATERIAL",
			1 => "MANUFACTURER",
			2 => "WIDTH",
			3 => "LENGHT",
			4 => "HEIGHT",
			5 => "",
		),
		"FILTER_PRICE_CODE" => array(
			0 => "BASE",
		),
		"FILTER_OFFERS_FIELD_CODE" => array(
			0 => "",
			1 => "",
		),
		"FILTER_OFFERS_PROPERTY_CODE" => array(
			0 => "",
			1 => "",
		),
		"COMPARE_NAME" => "CATALOG_COMPARE_LIST",
		"COMPARE_FIELD_CODE" => array(
			0 => "NAME",
			1 => "DETAIL_PICTURE",
			2 => "",
		),
		"COMPARE_PROPERTY_CODE" => array(
			0 => "MATERIAL",
			1 => "COLOR",
			2 => "MECH_KOL",
			3 => "SUVENIR_NAZNACH",
			4 => "PLATFORM",
			5 => "COMPLECT",
			6 => "ARB_TIME",
			7 => "CAMERA_TYPE",
			8 => "MANUFACTURER",
			9 => "DISPLAY_TYPE",
			10 => "ENERGY_TYPE",
			11 => "MATRIX_TYPE",
			12 => "CAMERA_POSITION",
			13 => "DIAGONAL",
			14 => "ARB_CHANNEL",
			15 => "VOLUME",
			16 => "PX_SUMM",
			17 => "MATRIX",
			18 => "OBJOM_VSTROENNOY_PAMYATI",
			19 => "SIZE_ACCUMUL",
			20 => "FORM_FACTOR",
			21 => "DYSPLAY_CAM",
			22 => "VIDEO_RESIZED",
			23 => "SUMM_SIM",
			24 => "CHASTOTA",
			25 => "PERSONAL_SIZE",
			26 => "FORMAT_SIM",
			27 => "IMPEDANS",
			28 => "",
			29 => "",
			30 => "",
			31 => "",
		),
		"COMPARE_OFFERS_FIELD_CODE" => array(
			0 => "",
			1 => "",
		),
		"COMPARE_OFFERS_PROPERTY_CODE" => array(
			0 => "",
			1 => "",
		),
		"COMPARE_ELEMENT_SORT_FIELD" => "sort",
		"COMPARE_ELEMENT_SORT_ORDER" => "asc",
		"DISPLAY_ELEMENT_SELECT_BOX" => "N",
		"COMPARE_SCROLL_UP" => "Y",
		"ALSO_BUY_ELEMENT_COUNT" => "5",
		"ALSO_BUY_MIN_BUYES" => "1",
		"DETAIL_BRAND_PROP_CODE" => "MANUFACTURER",
		"SHOW_DESCRIPTION_AFTER_SECTION" => "Y",
		"ZOOM_ON" => "Y",
		"SEF_URL_TEMPLATES" => array(
			"sections" => "",
			"section" => "#SECTION_CODE#/",
			"element" => "#SECTION_CODE#/#ELEMENT_CODE#/",
			"compare" => "compare.php?action=#ACTION_CODE#",
		),
		"VARIABLE_ALIASES" => array(
			"compare" => array(
				"ACTION_CODE" => "action",
			),
		)
	),
	false
);?>
<div class="container">
		<?$APPLICATION->IncludeComponent(
			"bitrix:catalog.bigdata.products",
			"",
			Array(
				"COMPONENT_TEMPLATE" => ".default",
				"RCM_TYPE" => "any",
				"ID" => $GLOBALS["CURRENT_ELEMENT_ID"],
				"IBLOCK_TYPE" => "catalog",
				"IBLOCK_ID" => "",
				"SHOW_FROM_SECTION" => "N",
				"HIDE_NOT_AVAILABLE" => "N",
				"SHOW_DISCOUNT_PERCENT" => "Y",
				"PRODUCT_SUBSCRIPTION" => "N",
				"SHOW_NAME" => "Y",
				"SHOW_IMAGE" => "Y",
				"MESS_BTN_BUY" => "Купить",
				"MESS_BTN_DETAIL" => "Подробнее",
				"MESS_BTN_SUBSCRIBE" => "Подписаться",
				"PAGE_ELEMENT_COUNT" => "5",
				"LINE_ELEMENT_COUNT" => "5",
				"TEMPLATE_THEME" => "blue",
				"DETAIL_URL" => "",
				"CACHE_TYPE" => "A",
				"CACHE_TIME" => "3601",
				"CACHE_GROUPS" => "Y",
				"SHOW_OLD_PRICE" => "N",
				"PRICE_CODE" => array("BASE"),
				"SHOW_PRICE_COUNT" => "1",
				"PRICE_VAT_INCLUDE" => "Y",
				"CONVERT_CURRENCY" => "N",
				"BASKET_URL" => "/personal/basket/",
				"ACTION_VARIABLE" => "action",
				"PRODUCT_ID_VARIABLE" => "id",
				"ADD_PROPERTIES_TO_BASKET" => "Y",
				"PRODUCT_PROPS_VARIABLE" => "prop",
				"PARTIAL_PRODUCT_PROPERTIES" => "N",
				"USE_PRODUCT_QUANTITY" => "N",
				"SHOW_PRODUCTS_6" => "Y",
				"SHOW_PRODUCTS_10" => "N",
				"PROPERTY_CODE_6" => array("SPECIALOFFER", "NEWPRODUCT", "SALELEADER", ""),
				"CART_PROPERTIES_6" => array("", ""),
				"ADDITIONAL_PICT_PROP_6" => "MORE_PHOTO",
				"LABEL_PROP_6" => "-",
				"PROPERTY_CODE_7" => array("", ""),
				"CART_PROPERTIES_7" => array("VOLUME", "COLOR", ""),
				"ADDITIONAL_PICT_PROP_7" => "",
				"OFFER_TREE_PROPS_7" => array("VOLUME", "COLOR")
			)
		);?>
	</div>
<?require($_SERVER["DOCUMENT_ROOT"]."/bitrix/footer.php");?>