<?
require($_SERVER['DOCUMENT_ROOT'].'/bitrix/header.php');
$APPLICATION->SetTitle("Главная");
?><?$APPLICATION->IncludeComponent(
	"alexkova.emarket:catalog.bestsellers",
	".default",
	Array(
		"IBLOCK_TYPE" => "catalog",
		"IBLOCK_ID" => "#PRODUCT_IBLOCK_ID#",
		"CACHE_TYPE" => "A",
		"CACHE_TIME" => "0",
		"ELEMENT_SORT_FIELD" => "sort",
		"ELEMENT_SORT_ORDER" => "asc",
		"ELEMENT_SORT_FIELD2" => "id",
		"ELEMENT_SORT_ORDER2" => "desc",
		"FILTER_NAME" => "arrFilter",
		"INCLUDE_SUBSECTIONS" => "Y",
		"SHOW_ALL_WO_SECTION" => "Y",
		"HIDE_NOT_AVAILABLE" => "N",
		"PAGE_ELEMENT_COUNT" => "30",
		"OFFERS_LIMIT" => "5",
		"CACHE_GROUPS" => "Y",
		"CACHE_FILTER" => "N",
		"PRICE_CODE" => array(0=>"BASE",1=>"Опт",),
		"USE_PRICE_COUNT" => "N",
		"SHOW_PRICE_COUNT" => "1",
		"PRICE_VAT_INCLUDE" => "Y",
		"CONVERT_CURRENCY" => "N",
		"BASKET_URL" => "#SITE_DIR#personal/basket.php",
		"ACTION_VARIABLE" => "action",
		"PRODUCT_ID_VARIABLE" => "id",
		"USE_PRODUCT_QUANTITY" => "N",
		"ADD_PROPERTIES_TO_BASKET" => "Y",
		"PRODUCT_PROPS_VARIABLE" => "prop",
		"PARTIAL_PRODUCT_PROPERTIES" => "N",
		"PRODUCT_PROPERTIES" => array(0=>"SPECIALOFFER",1=>"NEWPRODUCT",2=>"SALELEADER",3=>"RECOMMENDED",),
		"PRODUCT_QUANTITY_VARIABLE" => "quantity",
		"BESTSELLER_IBLOCK_TYPE" => "content",
		"BESTSELLER_IBLOCK_ID" => "#BESTSELLERS_IBLOCK_ID#",
		"OFFERS_SORT_FIELD" => "sort",
		"OFFERS_SORT_ORDER" => "asc",
		"OFFERS_SORT_FIELD2" => "id",
		"OFFERS_SORT_ORDER2" => "desc",
		"OFFERS_CART_PROPERTIES" => array()
	)
);?>
<?$APPLICATION->IncludeComponent(
	"alexkova.emarket:catalog.markers",
	".default",
	array(
		"IBLOCK_TYPE" => "catalog",
		"IBLOCK_ID" => "#PRODUCT_IBLOCK_ID#",
		"CACHE_TYPE" => "N",
		"CACHE_TIME" => "0",
		"ELEMENT_SORT_FIELD" => "sort",
		"ELEMENT_SORT_ORDER" => "asc",
		"ELEMENT_SORT_FIELD2" => "id",
		"ELEMENT_SORT_ORDER2" => "desc",
		"FILTER_NAME" => "arrFilter",
		"INCLUDE_SUBSECTIONS" => "Y",
		"SHOW_ALL_WO_SECTION" => "Y",
		"HIDE_NOT_AVAILABLE" => "N",
		"PAGE_ELEMENT_COUNT" => "20",
		"OFFERS_LIMIT" => "5",
		"CACHE_GROUPS" => "Y",
		"CACHE_FILTER" => "N",
		"PRICE_CODE" => array(
			0 => "BASE",
			1 => "Опт",
		),
		"USE_PRICE_COUNT" => "N",
		"SHOW_PRICE_COUNT" => "1",
		"PRICE_VAT_INCLUDE" => "Y",
		"CONVERT_CURRENCY" => "N",
		"BASKET_URL" => "/personal/basket.php",
		"ACTION_VARIABLE" => "action",
		"PRODUCT_ID_VARIABLE" => "id",
		"USE_PRODUCT_QUANTITY" => "N",
		"ADD_PROPERTIES_TO_BASKET" => "Y",
		"PRODUCT_PROPS_VARIABLE" => "prop",
		"PARTIAL_PRODUCT_PROPERTIES" => "N",
		"PRODUCT_PROPERTIES" => array(
			0 => "SPECIALOFFER",
			1 => "NEWPRODUCT",
			2 => "SALELEADER",
			3 => "RECOMMENDED",
		),
		"PRODUCT_QUANTITY_VARIABLE" => "quantity",
		"BESTSELLER_IBLOCK_TYPE" => "content",
		"BESTSELLER_IBLOCK_ID" => "#BESTSELLERS_IBLOCK_ID#",
		"OFFERS_SORT_FIELD" => "sort",
		"OFFERS_SORT_ORDER" => "asc",
		"OFFERS_SORT_FIELD2" => "id",
		"OFFERS_SORT_ORDER2" => "desc",
		"OFFERS_CART_PROPERTIES" => array(
		)
	),
	false
);?>

<div class="container">
<?$APPLICATION->IncludeComponent(
	"bitrix:catalog.bigdata.products",
	"",
	Array(
		"COMPONENT_TEMPLATE" => ".default",
		"RCM_TYPE" => "any",
		"ID" => '',
		"IBLOCK_TYPE" => "catalog",
		"IBLOCK_ID" => "",
		"SHOW_FROM_SECTION" => "N",
		"HIDE_NOT_AVAILABLE" => "N",
		"SHOW_DISCOUNT_PERCENT" => "Y",
		"PRODUCT_SUBSCRIPTION" => "N",
		"SHOW_NAME" => "Y",
		"SHOW_IMAGE" => "Y",
		"MESS_BTN_BUY" => "Купить",
		"MESS_BTN_DETAIL" => "Подробнее",
		"MESS_BTN_SUBSCRIBE" => "Подписаться",
		"PAGE_ELEMENT_COUNT" => "5",
		"LINE_ELEMENT_COUNT" => "5",
		"TEMPLATE_THEME" => "blue",
		"DETAIL_URL" => "",
		"CACHE_TYPE" => "A",
		"CACHE_TIME" => "3601",
		"CACHE_GROUPS" => "Y",
		"SHOW_OLD_PRICE" => "N",
		"PRICE_CODE" => array("BASE"),
		"SHOW_PRICE_COUNT" => "1",
		"PRICE_VAT_INCLUDE" => "Y",
		"CONVERT_CURRENCY" => "N",
		"BASKET_URL" => "/personal/basket/",
		"ACTION_VARIABLE" => "action",
		"PRODUCT_ID_VARIABLE" => "id",
		"ADD_PROPERTIES_TO_BASKET" => "Y",
		"PRODUCT_PROPS_VARIABLE" => "prop",
		"PARTIAL_PRODUCT_PROPERTIES" => "N",
		"USE_PRODUCT_QUANTITY" => "N",
		"SHOW_PRODUCTS_6" => "Y",
		"SHOW_PRODUCTS_10" => "N",
		"PROPERTY_CODE_6" => array("SPECIALOFFER", "NEWPRODUCT", "SALELEADER", ""),
		"CART_PROPERTIES_6" => array("", ""),
		"ADDITIONAL_PICT_PROP_6" => "MORE_PHOTO",
		"LABEL_PROP_6" => "-",
		"PROPERTY_CODE_7" => array("", ""),
		"CART_PROPERTIES_7" => array("VOLUME", "COLOR", ""),
		"ADDITIONAL_PICT_PROP_7" => "",
		"OFFER_TREE_PROPS_7" => array("VOLUME", "COLOR")
	)
);?>
	</div>
<?
require($_SERVER['DOCUMENT_ROOT'].'/bitrix/footer.php');
?>